//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DENETİM
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEGERLENDIRME
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DEGERLENDIRME()
        {
            this.DENETIMSONUC = new HashSet<DENETIMSONUC>();
        }
    
        public int ID { get; set; }
        public string SONUC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DENETIMSONUC> DENETIMSONUC { get; set; }
    }
}
