//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DENETİM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DENETİMEntities1 : DbContext
    {
        public DENETİMEntities1()
            : base("name=DENETİMEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BASLIK> BASLIK { get; set; }
        public virtual DbSet<BASLIKALT> BASLIKALT { get; set; }
        public virtual DbSet<BOLUM> BOLUM { get; set; }
        public virtual DbSet<DEGERLENDIRME> DEGERLENDIRME { get; set; }
        public virtual DbSet<DENETIM> DENETIM { get; set; }
        public virtual DbSet<DENETIMSONUC> DENETIMSONUC { get; set; }
        public virtual DbSet<KATEGORI> KATEGORI { get; set; }
        public virtual DbSet<KULLANICI> KULLANICI { get; set; }
        public virtual DbSet<MADDELER> MADDELER { get; set; }
        public virtual DbSet<SONUC> SONUC { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TUR> TUR { get; set; }
        public virtual DbSet<DDOKUMANLAR> DDOKUMANLAR { get; set; }
        public virtual DbSet<DSTANDARTLAR> DSTANDARTLAR { get; set; }
        public virtual DbSet<KISALTMALAR> KISALTMALAR { get; set; }
        public virtual DbSet<TERIMLER> TERIMLER { get; set; }
    }
}
