//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DENETİM
{
    using System;
    using System.Collections.Generic;
    
    public partial class DENETIMSONUC
    {
        public int ID { get; set; }
        public int DENETIM_ID { get; set; }
        public int DENETIM_KATEGORI { get; set; }
        public string DENETIM_YER { get; set; }
        public System.DateTime DENETİM_BASTARIH { get; set; }
        public System.DateTime DENETIM_BITTARIH { get; set; }
        public int DEGERLENDIRME_SONUC { get; set; }
        public int DENETIM_PUAN { get; set; }
    
        public virtual DEGERLENDIRME DEGERLENDIRME { get; set; }
        public virtual DENETIM DENETIM { get; set; }
        public virtual DENETIM DENETIM1 { get; set; }
        public virtual KATEGORI KATEGORI { get; set; }
    }
}
