//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DENETİM
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSTANDARTLAR
    {
        public int ID { get; set; }
        public string STANDART_NO { get; set; }
        public string STANDART_AD { get; set; }
        public string STANDART_NO2 { get; set; }
        public string STANDART_AD2 { get; set; }
    }
}
