//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DENETİM
{
    using System;
    using System.Collections.Generic;
    
    public partial class KISALTMALAR
    {
        public int ID { get; set; }
        public string KISALTMA_AD { get; set; }
        public string KISALTMA_TANIM { get; set; }
    }
}
