//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DENETİM
{
    using System;
    using System.Collections.Generic;
    
    public partial class KULLANICI
    {
        public int ID { get; set; }
        public string KULLANICI_TC { get; set; }
        public string KULLANICI_AD { get; set; }
        public string KULLANICI_SOYAD { get; set; }
        public string KULLANICI_UNVAN { get; set; }
        public string KULLANICI_MESLEK { get; set; }
        public string KULLANICI_SIFRE { get; set; }
    }
}
