//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DENETİM
{
    using System;
    using System.Collections.Generic;
    
    public partial class MADDELER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MADDELER()
        {
            this.DENETIM = new HashSet<DENETIM>();
        }
    
        public int ID { get; set; }
        public int BOLUM_NO { get; set; }
        public int BOLUM_AD { get; set; }
        public int BASLIK_NO { get; set; }
        public int BASLIK_AD { get; set; }
        public int BASLIKALT_NO { get; set; }
        public int BASLIKALT_AD { get; set; }
        public double MADDE_NO { get; set; }
        public string MADDE_TANIM { get; set; }
        public int MADDE_KATEGORI { get; set; }
        public int MADDE_TUR { get; set; }
        public int MADDE_PUAN { get; set; }
        public string MADDE_NOT { get; set; }
    
        public virtual BASLIK BASLIK { get; set; }
        public virtual BASLIK BASLIK1 { get; set; }
        public virtual BASLIKALT BASLIKALT { get; set; }
        public virtual BASLIKALT BASLIKALT1 { get; set; }
        public virtual BOLUM BOLUM { get; set; }
        public virtual BOLUM BOLUM1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DENETIM> DENETIM { get; set; }
        public virtual KATEGORI KATEGORI { get; set; }
        public virtual TUR TUR { get; set; }
        public virtual TUR TUR1 { get; set; }
    }
}
